service: tutor-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: java11
  timeout: 15
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
        - "s3:*"
      Resource: "*"

  # change stage when deploying dev stack
  stage: prod
  region: us-east-1

package:
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  user:
    handler: com.tutor.user.UserHandler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /user/{id}
          method: any
          integration: lambda
          request:
            parameters:
              paths:
                id: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /user/addReview/{userId}
          method: put
          integration: lambda
          request:
            parameters:
              paths:
                userId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
  request:
    handler: com.tutor.request.RequestsHandler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /request/{requestId}
          method: any
          integration: lambda
          request:
            parameters:
              paths:
                requestId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /request
          method: post
          integration: lambda
          request:
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /request/getRequestsByUserId/{userId}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                userId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /request/getAllMatchedRequests/{userId}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                userId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /request/getAllNonUndecidedRequests/{userId}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                userId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\

  matching:
    handler: com.tutor.matching.MatchingHandler
    # make sure we don't invoke tons of concurrent stream responses here
    reservedConcurrency: 1
    environment:
      STAGE: ${self:provider.stage}
#      disabled until prod time
#    events:
#      - stream:
#          type: dynamodb
#          arn:
#            Fn::GetAtt: [ requestsTable, StreamArn ]
#          maximumRetryAttempts: 0

  matches:
    handler: com.tutor.matches.MatchesHandler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /matches/updateMatch/{requestId}
          method: put
          integration: lambda
          request:
            parameters:
              paths:
                requestId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
  subjects:
    handler: com.tutor.subject.SubjectsHandler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /subject/
          method: get
          integration: lambda
          request:
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
  chat:
    handler: com.tutor.chat.ChatHandler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /chat/appendMessage/{chatId}
          method: put
          integration: lambda
          request:
            parameters:
              paths:
                chatId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /chat/
          method: post
          integration: lambda
          request:
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /chat/{chatId}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                chatId: true
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\
      - http:
          path: /chat/getPresetMessages
          method: get
          integration: lambda
          request:
            template:
              application/json: ${file(./mapping_template.yml):mapping_template}\

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    requestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: requestTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: requestId
            AttributeType: S
        KeySchema:
          - AttributeName: requestId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    chatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chatTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    requestDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: request-normalized-data-${self:provider.stage}