name: Backend Build + Test + Lint

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**'
  push:
    paths:
      - 'backend/**'

jobs:
  build-and-lint:
    name: Build backend components
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and test project with Maven
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB }}
        working-directory: ./backend/TutorTrade
        run: mvn clean install
      - name: Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
      - name: Lint files in backend directory
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_JAVA: true
          JAVA_FILE_NAME: google_checks.xml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




